# Generated by Django 2.1.4 on 2019-04-30 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bizcircle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(unique=True)),
                ('city_name', models.CharField(max_length=20)),
                ('bizcircle_id', models.IntegerField(unique=True)),
                ('bizcircle_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=20, unique=True)),
                ('final_price', models.FloatField()),
                ('sign_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=50)),
                ('build_addr', models.CharField(max_length=100)),
                ('open_time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('desc', models.CharField(max_length=255)),
                ('building_count', models.IntegerField()),
                ('house_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_price', models.FloatField()),
                ('frame_area', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
    ]
