# Generated by Django 2.1.4 on 2019-05-01 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190501_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bizcircle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bizcircle'),
        ),
    ]
