# Generated by Django 2.1.4 on 2019-05-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.AddField(
            model_name='order',
            name='city_id',
            field=models.IntegerField(default=0),
        ),
    ]
